### ISSUE TITLE
running party raises error - ModuleNotFoundError: No module named 'main'

### ISSUE THREAD

**Issue by Kovinda** [santiagobasulto/party-parrot#2]
I'm using the anaconda distribution.
I installed party-parrot using pip

upon running party

I get this error :
Traceback (most recent call last):
  File "d:\anaconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\Scripts\party.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'main'

**Comment by santiagobasulto** [comment]
I'm sorry but I can't replicate this. I never tried this on Windows, so Idk if it's a packaging issue with conda or a windows issue. PRs are welcome though.
